### PR TITLE
try an old db version to see if it fixes tests

### PR DESCRIPTION
**Pull request by blankdots**
this is just to try to see if it fixes, no need to do anything about it.

### CODE REVIEW

**Comment by blankdots** [comment]
the problem seems to be with mq `LEGA_mq.1.no1h7xsm7153@fv-az292-702    | client unexpectedly closed TCP connection`

**Comment by blankdots** [comment]
closing as purpose (testing) was achieved.

**Comment by a-ghanem** [comment]
I will try to revert the changes in the sda-pipeline services and see if it works.

**Comment by blankdots** [comment]
random guess: maybe related https://github.com/neicnordic/sda-pipeline/issues/325 :man_shrugging:

**Comment by a-ghanem** [comment]
@blankdots could be.

**Comment by a-ghanem** [comment]
Solves the issue of the failing tests. Approve.

**Pull request merged**
